custom:
    [
        "https://github.com/Flysoft-Studio/Platinum/blob/main/Platinum/img/sponsor/alipay.jpg",
        "https://github.com/Flysoft-Studio/Platinum/blob/main/Platinum/img/sponsor/wx.png",
    ]
